app:
    resource: '@AppBundle/Controller/'
    type: annotation

livre_delete:
    path:       /book/{id}/delete
    defaults:   { _controller: AppBundle:Livre:deleteBook }

livre_emprunt:
    path:       /book/{id}/emprunt
    defaults:   { _controller: AppBundle:Livre:managePret }

livre:
    path:       /book/{id}
    defaults:   { _controller: AppBundle:Livre:book }
